apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fu9fuoh21-go 
  janus-idp.io/tekton: fu9fuoh21-go
  backstage.io/kubernetes-id: fu9fuoh21-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fu9fuoh21-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml