apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fu9fuoh21-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fu9fuoh21-go 
  name: fu9fuoh21-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fu9fuoh21-go 
